pipeline {
    agent { label 'nodejs' }
     tools {nodejs "nodejs"}

    // Set your OCP project
    environment { APP_NAMESPACE = 'xudlbs-metrics' }

    stages{
        stage('Check') {
            sh " pwd "
            sh " ls -altr DO400-apps-solutions/greeting-cd-pipeline"
        } 

        stage('Test') {
            steps {
                dir('DO400-apps-solutions/greeting-cd-pipeline')
                sh "node test.js"
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    oc start-build greeting-metrics \
                    --follow --wait -n xudlbs-metrics
                '''
            }

        }

        // Add more stages here
    }
}
