pipeline {

    agent {node { label 'maven'}}
     tools {maven "maven"}
     environment { APP_NAMESPACE = 'xudlbs-security-scans'}
     stages {
        stage('Test') {
            steps {
                sh 'pwd'
                sh 'ls altr'
                dir('shopping-cart') {
                    sh 'pwd'
                    sh 'ls -altr'
                    sh 'mvn clean test'
                }
            }
        }
     
     stage('Image build') {
        steps {
            dir('shopping-cart') {
                sh """
                oc start-build security-scans --follow --wait -n ${APP_NAMESPACE}
                """
            }
        }
     }
     stage('Deploy') {
        steps {
            dir('shopping-cart') {
                sh """
                oc patch deployment security-scans \
                -p '{"spec": {"template": {"metadata": {"labels": {"build": "build-${BUILD_NUMBER}"}}}}}' \
                -n ${APP_NAMESPACE}
                """
                }
            }
        }
     }
}