pipeline {

    agent {node { label 'maven'}}
     tools {maven "maven"}
     environment { APP_NAMESPACE = 'xudlbs-security-scans'}
     stages {
        stage('Test') {
            steps {
                sh 'pwd'
                sh 'ls -altr'
                dir('DO400-apps-solutions/shopping-cart') {
                    sh 'pwd'
                    sh 'ls -altr'
                    sh 'mvn clean test'
                }
            }
        }
     
     stage('Image build') {
        steps {
            dir('DO400-apps-solutions/shopping-cart') {
                sh """
                oc start-build security-scans --follow --wait -n ${APP_NAMESPACE}
                """
            }
        }
     }
     stage('Security Scan') {
        steps {
            dir('DO400-apps-solutions/shopping-cart') {
                
            sh " pwd"
           sh "ls -altr"
           sh " ls -altr kubefiles;"
          sh "  cat kubefiles/security-scan-template.yml"    
                sh """
oc process --local -f kubefiles/security-scan-template.yml -p PROJECT_NAME=xudlbs-security-scans \
 -p CVE_CODE=CVE-2020-14583 | oc replace --force -n xudlbs-security-scans -f -
                """
                sh "! ../tools/check-job-state.sh security-scans-trivy ${APP_NAMESPACE}"
            }
        }
     }
     stage('Deploy') {
        steps {
            dir('DO400-apps-solutions/shopping-cart') {
                sh """
                oc patch deployment security-scans \
                -p '{"spec": {"template": {"metadata": {"labels": {"build": "build-${BUILD_NUMBER}"}}}}}' \
                -n ${APP_NAMESPACE}
                """
                }
            }
        }
     }
}